[package]
name = "Checkers"
description = "Game of checkers"
version = "0.0.1"
readme = "README.md"
license = "gpl3"
repository = "https://example.com"
authors = [ "szymon-jozef" ]

edition = "2024"

[dependencies]
env_logger = "0.11.11"
log = "0.4.33"

[dependencies.uuid]
version = "1.24.0"
features = [
    "v4",
]
